tasks:
  - init: (cd node-manager; npm install)
  - init: (cd node-manager; pip3 install -r requirements.txt)
  - init: (cd node-agent; npm install)
image:
  file: .gitpod.Dockerfile
ports:
  - port: 3512
    onOpen: ignore