---

- name: Prepare files
  hosts: all # this can be overwritten with the --limit option when starting the playbook
  tasks:
    - name: Create Container Directory, if it does not Exist
      file:
        path: "{{ container_dirname }}"
        state: directory
        mode: "0755"
      become: yes

    - name: Synchronize Local Directory
      synchronize:
        src: "{{ playbook_dir }}/../run/{{ local_dirname }}/"
        dest: "{{ container_dirname }}"
      become: yes

    - name: Install Docker SDK
      pip:
        name: docker
      become: yes

    - name: Start Docker Service
      service:
        name: docker
        state: started
      become: yes

    - name: Pull Docker Image
      docker_image:
        name: "{{ docker_image }}"
        source: pull
        force_source: yes
