---

- name: Start Container on Machines
  hosts: all # this can be overwritten with the --limit option when starting the playbook
  tasks:
    - name: Remove Existing Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: absent
    - name: Start Container
      docker_container:
        name: "{{ container_name }}"
        image: "{{ docker_image }}"
        state: started
        network_mode: host
        restart_policy: on-failure
        log_driver: journald
        env_file: "{{ container_dirname }}/env_file.env"
        volumes:
          - "{{ container_dirname }}:{{ container_dirname }}"